runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /api/.*
  script: backend.api.application
#  secure: always

- url: /_ah/warmup
  script: backend.api.warmup
  login: admin

- url: /api/movies
  script: backend.api.test.check

- url: /index
  script: frontend.app

- url: /delete
  script: frontend.app

- url: /api/movie/titles
  script: api.movie.Titles

- url: /api/movie/titles/page/<int:page_number>
  script: api.movie.Titles

inbound_services:
- warmup